# Generated by Django 3.2.3 on 2021-05-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0002_movie_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
