# Generated by Django 3.2.3 on 2021-07-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0006_auto_20210723_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pclass', models.IntegerField()),
                ('sex', models.IntegerField()),
                ('age', models.IntegerField()),
                ('sibsp', models.IntegerField()),
                ('parents', models.IntegerField()),
                ('fare', models.IntegerField()),
                ('embarked', models.IntegerField()),
                ('title', models.IntegerField()),
            ],
        ),
    ]
